name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.4+10

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  animated_bottom_navigation_bar: ^0.3.2
  apple_sign_in: ^0.1.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.0
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  flutter_custom_tabs: ^1.0.2
  flutter_facebook_login: ^3.0.0
  flutter_html: ^2.1.1
  flutter_icons: ^1.1.0
  flutter_widget_from_html: ^0.6.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  html: ^0.15.0
  html_unescape: ^2.0.0
  image_picker: ^0.8.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  lottie: ^1.1.0
  md2_tab_indicator: ^1.0.2
  package_info: ^2.0.2
  path_provider: ^2.0.2
  provider: ^5.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  skeleton_text: ^3.0.0

  toast: ^0.1.5
  url_launcher: ^6.0.9
  youtube_player_flutter: ^8.0.0
  animated_progress_button: ^1.0.2+1
  rounded_loading_button: ^2.0.5
  firebase_analytics: ^8.2.0
  # firebase_admob: ^0.10.2
  # facebook_audience_network: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


  

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png
    - assets/news6.png
    - assets/news7.png
    - assets/splash.png
    - assets/done.json
    - assets/translations/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
